// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2_zgnghVb6Gsq7jm49hCr_XNDPgMSdOU',
    appId: '1:956848209864:web:90bc7b35ca751fac01cafd',
    messagingSenderId: '956848209864',
    projectId: 'todo-app-53615',
    authDomain: 'todo-app-53615.firebaseapp.com',
    storageBucket: 'todo-app-53615.appspot.com',
    measurementId: 'G-HCV9ZJ1Q1P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYBciR_Zc6upaQnmsie-46KbdShP2bRoE',
    appId: '1:956848209864:android:e3f06541847ed4ed01cafd',
    messagingSenderId: '956848209864',
    projectId: 'todo-app-53615',
    storageBucket: 'todo-app-53615.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbubVqhleGX_cuiGnXYmhM1UxbPNTAftU',
    appId: '1:956848209864:ios:b98ba19863aaa23301cafd',
    messagingSenderId: '956848209864',
    projectId: 'todo-app-53615',
    storageBucket: 'todo-app-53615.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbubVqhleGX_cuiGnXYmhM1UxbPNTAftU',
    appId: '1:956848209864:ios:b98ba19863aaa23301cafd',
    messagingSenderId: '956848209864',
    projectId: 'todo-app-53615',
    storageBucket: 'todo-app-53615.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2_zgnghVb6Gsq7jm49hCr_XNDPgMSdOU',
    appId: '1:956848209864:web:4b6c27b3a303390101cafd',
    messagingSenderId: '956848209864',
    projectId: 'todo-app-53615',
    authDomain: 'todo-app-53615.firebaseapp.com',
    storageBucket: 'todo-app-53615.appspot.com',
    measurementId: 'G-JL0YBJCMKY',
  );

}